{% set version = "29.0.0" %}
{% set name = "gherkin-official" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
    sha256: dbea32561158f02280d7579d179b019160d072ce083197625e2f80a6776bb9eb
  - url: https://github.com/cucumber/gherkin/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 52f0a6c7f0057c72e9934eba3e43a651a3791e81624191f559cdebf101b8db66
    folder: gh_src

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - nose

test:
  source_files:
    - gh_src/python
  imports:
    - gherkin
  requires:
    - pip
    - pytest >= 5.0
  commands:
    - pip check
    - cd gh_src/python
    - pytest -vvv test

about:
  home: https://github.com/cucumber/gherkin
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Gherkin parser/compiler for Python
  description: |
    Gherkin uses a set of special keywords to give structure and meaning to executable specifications. 
    Each keyword is translated to many spoken languages; in this reference we'll use English.
  dev_url: https://github.com/cucumber/gherkin
  doc_url: https://cucumber.io/docs/gherkin

extra:
  recipe-maintainers:
    - mariusvniekerk
