{% set version = "4.1.3" %}

package:
  name: gherkin-official
  version: {{ version }}

source:
  fn: gherkin-official-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/gherkin-official/gherkin-official-{{ version }}.tar.gz
  sha256: 7f6fa7a3ceffda8bba0f56b42140cc6bae001d010fef336b5b2602252242395d

build:
  number: 1005
  script:
    - rm gherkin/count_symbols_py2.py  # [py3k and not win]
    - del gherkin\count_symbols_py2.py  # [py3k and win]
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - nose

test:
  imports:
    - gherkin

about:
  home: https://github.com/cucumber/gherkin-python
  license: MIT
  # xref: https://github.com/cucumber/gherkin-python/pull/7
  license_file: '{{ environ['RECIPE_DIR'] }}/LICENSE.txt'
  summary: Gherkin parser/compiler for Python

extra:
  recipe-maintainers:
    - mariusvniekerk
