# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "M/D3IOS+l6mhY3pqoCaKV1GSuXpjrQRFWxpkz3J5a5JPulslSEVuMmggqe/5XuH5khrLPPUerQ+wcylr2esQWCoQ194PIlvFVKdEdyujO5wP6FXCRyrSEJLjt/dn1iqxkDfT82mLA5qKFGtEa98NOYQe/ruF/isClY+K/Pinc4LNUMqgvvnJBSaiwQRqPXKky6xLxFvUvXzjpgOayrQRrKcCQ+PlC8VWk5eJE8UhiEYnL9O00lk+cBZaHhtEzXKZ1fwJq10CgK1Qf2ib8dlsaN3HigtFMxz4e/y3SM9fnCpdO0tFlDHlqOqxNUx44BpWBZjyb3w8h+XbdsKqL4h94Hv9LUF5q0lzqeOFVmiRNTGmcOqoRmuhSiL8jmQPHtGTbS/G9w9GSAkxRnpTh8Ksgqn9h//T4UNwnqPlfUuDQgamWGtu5UeJzJp2wVhp51uBvrv1gas6Lc1sIlhhNQQxMdakaEniIZqNnkZL2Yao/u838C4/mJTmwCbHkWVOxcz+PRcRm4JnbkCMfVw0y3Tft0a5owDvvs3Bx4sAgvLIm/csrVbvLMq9dBtdOFeRy7nt+kxrvTlFkX3h22MpzmY5JBlGundxPytD5vBuuNmhzYuLHISVCV5B+BozsyESp1H+5ms/EHa5xyhw8cQC+rzv8/7J2BVB/bP7msUs/z+bwVo="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
