travis:
  secure:
    BINSTAR_TOKEN: v9PmS9+MG0Mp/oNtLfzVm7Wzp+3nFqFVY2+9E4XpM8MgaTjheevqWoAFKFAeM/UgP/kqeRCsCOKr4w+vc2SxSThZsrRTNzX4d1U6FdLKoN19g/I85eua+3QpA55rVTRmIo4kOalXD7GqeaVA70mNqYpNNzSFrSzkkJk6X37AuZteIBNQfEUjAjIYJ2wVglxJLjG0DyXRvosTJFItqPM5ReKkJwxZGO+ERJJbfwsKJFY6VshaJfNDYzohkH3BHmD2quhryisX+SyLjx04HFEsvY/OThGMFMzgMku4mSZ1GhCxh0upt3WLdfq48plrZ36qSRPAqW+coeVlB7woabBRLEvAnURzRGSXsi6Q9cKuYUHDHAFthiHrMXNXt2wK0QYkjURD7g87tafxIvCuhdvPdWTH9Zh7fUTR8OvPZ0lNMI5uiYwYe/wOJkeECFx2jSmiWtnSN5GeuCF6GkzBbtsvkGD2r1prP7XixtE/VsFG6YeCmdRd4BZ0Y4ahiyl/9ZFsNG5IVCi1NIJ5keWRgdLoThznYpY/RoKWshAeYezlmBvew3+J+ld5oObxe7KAGnK1Uim54cJ8DxldUrIy8RBhTIJxL13qPpxWvHZx+F1zqlhdqFq7hG4JRwGpAAfMKdAmIU2nHb+eoiSnVz1ppQ234z4azFHBYYGoOnq/iCsolHs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
